name: oxcy
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # CORE UTILS
  http: ^1.2.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  rxdart: ^0.27.7

  # UI & DESIGN
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  glassmorphism: ^3.0.0
  fluentui_system_icons: ^1.1.225
  animations: ^2.1.1
  flutter_staggered_animations: ^1.1.1

  # STATE
  provider: ^6.1.5+1

  # ðŸŽµ AUDIO ENGINE
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  on_audio_query: ^2.9.0

  # YOUTUBE (Hemant's Fork)
  youtube_explode_dart:
    git:
      url: https://github.com/HemantKArya/youtube_explode_dart.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
