name: oxcy
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  # UI & Icons
  cupertino_icons: ^1.0.8
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1

  # State Management
  provider: ^6.1.5+1

  # ðŸŽµ AUDIO CORE (Himmy's Fixes)
  # 1. The Extractor: Turns YouTube IDs into playable links
  # REMOVE THIS:
  # youtube_explode_dart: ^3.0.5

  youtube_explode_dart:
    git:
      url: https://github.com/HemantKArya/youtube_explode_dart.git
      ref: master
  
  # 2. The Player: Plays the actual audio
  just_audio: ^0.9.46
  
  # 3. Background Play: Notification controls (Play/Pause in lock screen)
  just_audio_background: ^0.0.1-beta.11
  
  # 4. Audio Session: FIXES the "AndroidAudioAttributes" error! ðŸ› ï¸
  audio_session: ^0.1.21
  
  # 5. Local Files: The version that FIXES the Namespace Error ðŸ› ï¸
  on_audio_query: ^2.9.0 
  
  # 6. Permissions: Essential for Android 13+ music access
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
