name: oxcy
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # CORE UTILS
  http: ^1.2.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  rxdart: ^0.27.7

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  
  # STATE
  provider: ^6.1.5+1

  # ðŸŽµ THE MUSIFY ENGINE (MATCHED)
  # 1. The Player (Upgraded to Musify's version)
  just_audio: ^0.10.5
  
  # 2. Audio Service (Manual handling, no "background" wrapper)
  audio_service: ^0.18.18
  
  # 3. Audio Session (For focus handling)
  audio_session: ^0.1.21

  # 4. Local Files
  on_audio_query: ^2.9.0
  
  # 5. YouTube Extractor (Hemant's Fork - Keep this for online later)
  youtube_explode_dart:
    git:
      url: https://github.com/HemantKArya/youtube_explode_dart.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
